CREATE TABLE students(
                         student_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         first_name varchar(20) NOT NULL,
                         last_name varchar(30) NOT NULL,
                         email varchar(30) NOT NULL
);

CREATE TABLE subjects(
                         subject_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         subject_name varchar(20) NOT NULL
);

CREATE TABLE grades(
                       grade_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       student_id integer REFERENCES students(student_id),
                       subject_id integer REFERENCES subjects(subject_id),
                       grade integer NOT NULL
);