CREATE TABLE students(
student_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
first_name varchar(20) NOT NULL,
last_name varchar(30) NOT NULL,
email varchar(30) NOT NULL
);

CREATE TABLE subjects(
subject_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
subject_name varchar(20) NOT NULL
);

CREATE TABLE grades(
grade_id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
student_id integer REFERENCES students(student_id),
subject_id integer REFERENCES grades(subject_id),
grade integer NOT NULL
);

INSERT INTO students (first_name, last_name, email) 
VALUES 
('Jan', 'Kowalski', 'jan.kowalski@twojmail.com'),
('Patryk', 'Nowak', 'patryk.nowak@skrzyneczka.pl'),
('Barbara', 'Kwiatek', 'kwiatuszek@twojmail.com');

INSERT INTO subjects (subject_name)
VALUES 
('Matematyka'),
('Język Polski'),
('Język Angielski'),
('Historia'),
('Biologia');

INSERT INTO grades (student_id, subject_id, grade)
VALUES
(1,1,5),
(1,2,3),
(1,5,4),
(2,3,2),
(2,4,2),
(2,1,3),
(3,1,1),
(3,2,5),
(2,4,3);

