CREATE TABLE IF NOT EXISTS student_book.students (
                         id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         first_name varchar(20) NOT NULL,
                         last_name varchar(30) NOT NULL,
                         email varchar(30) NOT NULL
);
ALTER SEQUENCE student_book.students_id_seq RESTART WITH 4;

CREATE TABLE IF NOT EXISTS student_book.subjects (
                         id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         subject_name varchar(20) NOT NULL
);

ALTER SEQUENCE student_book.subjects_id_seq RESTART WITH 6;

CREATE TABLE IF NOT EXISTS student_book.grades (
                       id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       student_id integer REFERENCES student_book.students(id),
                       subject_id integer REFERENCES student_book.subjects(id),
                       grade integer NOT NULL
);

ALTER SEQUENCE student_book.grades_id_seq RESTART WITH 10;