create table if not exists student_book.classes (
id integer primary key generated by default as identity,
name varchar(20) not null,
);
insert into student_book.class_groups (id,name)
values
(1,'1A'),
(2,'1B'),
(3,'2A'),
(4,'3A'),
(5,'3B');

alter table if exists student_book.students
add column if not exists group_id integer REFERENCES student_book.class_groups(id);

update student_book.students
set group_id = 1 where id = 1 or id = 2
set group_id = 3 where id = 3;

create table if not exists student_book.teacher_group(
teacher_id integer REFERENCES student_book.teachers(id),
group_id integer REFERENCES student_book.class_groups(id),
primary key (teacher_id, class_id)
);

insert into student_book.teacher_class (teacher_id,group_id)
values
(1,1),
(1,3),
(1,4),
(2,2),
(2,3),
(2,4),
(2,5),
(3,1),
(3,2);