create table if not exists student_book.homeworks (
id integer primary key generated by default as identity,
group_id integer references student_book.class_groups(id),
teacher_id integer references student_book.teachers(id),
subject_id integer references student_book.subjects(id),
file_name varchar(50) not null,
file_description varchar(500),
file_data bytea
);