create table if not exists student_book.users (
id integer primary key generated by default as identity,
username varchar(20) not null,
password varchar(80) not null,
authority varchar(20) not null
);

insert into student_book.users (id,username,password,authority)
values
(1,'jasio','$2a$04$HNYYju5NtyEQqOUmKVIhiOr3QYqKRLIK/knGGhTX2WWrhgoDbySiu','ROLE_STUDENT'),
(2,'nauczyciel','$2a$04$ui6JGLAvSnZbjJnMlh4uhuUjN97Vk9/5l6VHYpX1HdX/F48KdVMCS','ROLE_TEACHER');

ALTER SEQUENCE student_book.users_id_seq RESTART WITH 3;
